image: registry.ymc.tools:443/docker-images/docker:latest

variables:
  MODOFU_DOCKER_IMAGE: modofu/modofu:stable

stages:
  - build

job_build_and_push:
  tags:
    - docker-image-build
    - push-to-dockerhub
  only:
    - master
    - wip/dabe/oss
  except:
    - tags
  stage: build
  script:
    - docker build --pull --build-arg MODOFU_DOCKER_IMAGE=$MODOFU_DOCKER_IMAGE -t $MODOFU_DOCKER_IMAGE ./
    - docker push $MODOFU_DOCKER_IMAGE

